service:
  name: leaveamessage-serverless
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - '*'
      Resource:  ["arn:aws:s3:::jcc-media1972/","arn:aws:s3:::jcc-media1972/*"]
    - Effect: 'Allow'
      Action:
        - '*'
      Resource:  ["arn:aws:s3:::jcc-media-out1972/","arn:aws:s3:::jcc-media-out1972/*"]  
    - Effect: 'Allow'
      Action: 
        - 'transcribe:*'
      Resource:  "*"  
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
functions:
  recordCall:
    handler: handler.recordCall
    environment:
      RECORDING_CALLBACK_URL: http://example.com/api/v1
    events:
      - http:
          method: post
          path:  recordCall
  recordingCallBack:
     handler: handler.recordingCallBack
     events:
      - http:
          method: post
          path: recordingCallBack
  recordingTranscriptInitiation:
     handler: handler.recordingTranscribeInit
     events:
        - s3:
            bucket: jcc-media1972
            event: s3:ObjectCreated:*
            rules:
              - prefix: media/
              - suffix: .wav
            existing: true